[project]
authors = ["Andrew Lin <andrew.lin@ieee.org>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "HSM.c"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cmake = ">=3.30.5,<4"
gcc = ">=14.1.0,<15"
